/*
 * JS for signUp generated by Appery.io
 */

Apperyio.getProjectGUID = function() {
    return '4af7b984-e374-46a6-b5a4-74c3c1e49ba9';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}

Apperyio.AppPages = [{
    "name": "welcome",
    "location": "welcome.html"
}, {
    "name": "startScreen",
    "location": "startScreen.html"
}, {
    "name": "signUp",
    "location": "signUp.html"
}, {
    "name": "sales",
    "location": "sales.html"
}, {
    "name": "login",
    "location": "login.html"
}];

function signUp_js() {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'lblSignUpName': 'signUp_lblSignUpName',
        'spacer_3': 'signUp_spacer_3',
        'lblSignUpEmail': 'signUp_lblSignUpEmail',
        'spacer_6': 'signUp_spacer_6',
        'btnSignUpSubmit': 'signUp_btnSignUpSubmit',
        'lblpopupsignup': 'signUp_lblpopupsignup'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    /*
     * Nonvisual components
     */

    Apperyio.mappings = Apperyio.mappings || {};

    Apperyio.mappings["signUp_sign_up_onsuccess_mapping_0"] = {
        "homeScreen": "signUp",
        "directions": [

        {
            "from_name": "sign_up",
            "from_type": "SERVICE_RESPONSE",

            "to_name": "CustomerID",
            "to_type": "LOCAL_STORAGE",

            "mappings": [

            {

                "source": "$['body']['CustomerID']",
                "target": "$"

            }

            ]
        },

        {
            "from_name": "sign_up",
            "from_type": "SERVICE_RESPONSE",

            "to_name": "Email",
            "to_type": "LOCAL_STORAGE",

            "mappings": [

            {

                "source": "$['body']['Email']",
                "target": "$"

            }

            ]
        },

        {
            "from_name": "sign_up",
            "from_type": "SERVICE_RESPONSE",

            "to_name": "Name",
            "to_type": "LOCAL_STORAGE",

            "mappings": [

            {

                "source": "$['body']['Name']",
                "target": "$"

            }

            ]
        },

        {
            "from_name": "sign_up",
            "from_type": "SERVICE_RESPONSE",

            "to_name": "signUp",
            "to_type": "UI",

            "mappings": [

            {

                "source": "$['body']['status']",
                "target": "$['lblpopupsignup:text']"

            }

            ]
        }

        ]
    };

    Apperyio.mappings["signUp_sign_up_onbeforesend_mapping_0"] = {
        "homeScreen": "signUp",
        "directions": [

        {
            "from_name": "signUp",
            "from_type": "UI",

            "to_name": "sign_up",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {},
                "parameters": {},
                "body": null
            },

            "mappings": [

            {

                "source": "$['lblSignUpName:text']",
                "target": "$['parameters']['name']"

            },

            {

                "source": "$['lblSignUpEmail:text']",
                "target": "$['parameters']['email']"

            }

            ]
        }

        ]
    };

    Apperyio.datasources = Apperyio.datasources || {};

    window.sign_up = Apperyio.datasources.sign_up = new Apperyio.DataSource(SignUp, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["signUp_sign_up_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {

        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["signUp_sign_up_onsuccess_mapping_0"]);
            var popupElement = Apperyio("mobilepopup_7");
            if (popupElement.popup("option", "positionTo") === "origin") {
                popupElement.popup("open", {
                    transition: "none",
                    positionTo: "#" + $(this).attr("id")
                });
            } else {
                popupElement.popup("open", {
                    transition: "none"
                });
            };
            var PopUp = Apperyio('lblpopupsignup');

            if (PopUp.text() == 'success') {
                Apperyio.navigateTo('welcome', {});
            };
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });

    Apperyio.CurrentScreen = 'signUp';
    _.chain(Apperyio.mappings).filter(function(m) {
        return m.homeScreen === Apperyio.CurrentScreen;
    }).each(Apperyio.UIHandler.hideTemplateComponents);

    /*
     * Events and handlers
     */

    // On Load
    var signUp_onLoad = function() {
            signUp_elementsExtraJS();

            signUp_deviceEvents();
            signUp_windowEvents();
            signUp_elementsEvents();
        };

    // screen window events


    function signUp_windowEvents() {

        $('#signUp').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });

    };

    // device events


    function signUp_deviceEvents() {
        document.addEventListener("deviceready", function() {

        });
    };

    // screen elements extra js


    function signUp_elementsExtraJS() {
        // screen (signUp) extra code

        /* mobilepopup_7 */
        $("#signUp_mobilepopup_7").popup("option", "positionTo", "window");

    };

    // screen elements handler


    function signUp_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });

        $(document).off("click", '#signUp_mobilecontainer [name="btnSignUpSubmit"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    try {
                        sign_up.execute({});
                    } catch (e) {
                        console.error(e);
                        hideSpinner();
                    };

                }
            },
        }, '#signUp_mobilecontainer [name="btnSignUpSubmit"]');

    };

    $(document).off("pagebeforeshow", "#signUp").on("pagebeforeshow", "#signUp", function(event, ui) {
        Apperyio.CurrentScreen = "signUp";
        _.chain(Apperyio.mappings).filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        }).each(Apperyio.UIHandler.hideTemplateComponents);
    });

    signUp_onLoad();
};

$(document).off("pagecreate", "#signUp").on("pagecreate", "#signUp", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    signUp_js();
});