/*
 * JS for welcome generated by Appery.io
 */

Apperyio.getProjectGUID = function() {
    return '4af7b984-e374-46a6-b5a4-74c3c1e49ba9';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}

Apperyio.AppPages = [{
    "name": "welcome",
    "location": "welcome.html"
}, {
    "name": "startScreen",
    "location": "startScreen.html"
}, {
    "name": "signUp",
    "location": "signUp.html"
}, {
    "name": "sales",
    "location": "sales.html"
}, {
    "name": "login",
    "location": "login.html"
}];

function welcome_js() {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'btnAllSales': 'welcome_btnAllSales',
        'mobilelabel_2': 'welcome_mobilelabel_2',
        'mobilelabel_10': 'welcome_mobilelabel_10',
        'mnuPlaces': 'welcome_mnuPlaces',
        'mnuPlaces-0': 'welcome_mnuPlaces-0',
        'spacer_12': 'welcome_spacer_12',
        'mobilelabel_11': 'welcome_mobilelabel_11',
        'mnuNumseats': 'welcome_mnuNumseats',
        'mnuNumseats-0': 'welcome_mnuNumseats-0',
        'mobilegrid_16': 'welcome_mobilegrid_16',
        'mobilegridcell_17': 'welcome_mobilegridcell_17',
        'mobilelabel_21': 'welcome_mobilelabel_21',
        'mobilegridcell_18': 'welcome_mobilegridcell_18',
        'lblQuote': 'welcome_lblQuote',
        'spacer_15': 'welcome_spacer_15',
        'btnQuote': 'welcome_btnQuote',
        'btnBook': 'welcome_btnBook',
        'lblbookstatus': 'welcome_lblbookstatus'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    /*
     * Nonvisual components
     */

    Apperyio.mappings = Apperyio.mappings || {};

    Apperyio.mappings["welcome_amount_onsuccess_mapping_0"] = {
        "homeScreen": "welcome",
        "directions": [

        {
            "from_name": "amount",
            "from_type": "SERVICE_RESPONSE",

            "to_name": "welcome",
            "to_type": "UI",

            "mappings": [

            {

                "source": "$['body']['Amount']",
                "target": "$['lblQuote:text']"

            }

            ]
        },

        {
            "from_name": "amount",
            "from_type": "SERVICE_RESPONSE",

            "to_name": "Amount",
            "to_type": "LOCAL_STORAGE",

            "mappings": [

            {

                "source": "$['body']['Amount']",
                "target": "$"

            }

            ]
        }

        ]
    };

    Apperyio.mappings["welcome_amount_onbeforesend_mapping_0"] = {
        "homeScreen": "welcome",
        "directions": [

        {
            "from_name": "welcome",
            "from_type": "UI",

            "to_name": "amount",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {},
                "parameters": {},
                "body": null
            },

            "mappings": [

            {

                "source": "$['mnuNumseats:selectedMenuItem']",
                "target": "$['parameters']['seats']"

            },

            {

                "source": "$['mnuPlaces:selectedMenuItem']",
                "target": "$['parameters']['destinationkey']"

            }

            ]
        },

        {
            "from_name": "welcome",
            "from_type": "UI",

            "to_name": "SeatCount",
            "to_type": "LOCAL_STORAGE",

            "mappings": [

            {

                "source": "$['mnuNumseats:selectedMenuItem']",
                "target": "$"

            }

            ]
        },

        {
            "from_name": "welcome",
            "from_type": "UI",

            "to_name": "DestinationKey",
            "to_type": "LOCAL_STORAGE",

            "mappings": [

            {

                "source": "$['mnuPlaces:selectedMenuItem']",
                "target": "$"

            }

            ]
        }

        ]
    };

    Apperyio.mappings["welcome_book_sale_onsuccess_mapping_0"] = {
        "homeScreen": "welcome",
        "directions": [

        {
            "from_name": "book_sale",
            "from_type": "SERVICE_RESPONSE",

            "to_name": "welcome",
            "to_type": "UI",

            "mappings": [

            {

                "source": "$['body']['status']",
                "target": "$['lblbookstatus:text']"

            }

            ]
        }

        ]
    };

    Apperyio.mappings["welcome_book_sale_onbeforesend_mapping_0"] = {
        "homeScreen": "welcome",
        "directions": [

        {
            "from_name": "Amount",
            "from_type": "LOCAL_STORAGE",

            "to_name": "book_sale",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {},
                "parameters": {},
                "body": null
            },

            "mappings": [

            {

                "source": "$",
                "target": "$['parameters']['Amount']"

            }

            ]
        },

        {
            "from_name": "Email",
            "from_type": "LOCAL_STORAGE",

            "to_name": "book_sale",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {},
                "parameters": {},
                "body": null
            },

            "mappings": [

            {

                "source": "$",
                "target": "$['parameters']['Email']"

            }

            ]
        },

        {
            "from_name": "CustomerID",
            "from_type": "LOCAL_STORAGE",

            "to_name": "book_sale",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {},
                "parameters": {},
                "body": null
            },

            "mappings": [

            {

                "source": "$",
                "target": "$['parameters']['CustomerKey']"

            }

            ]
        },

        {
            "from_name": "DestinationKey",
            "from_type": "LOCAL_STORAGE",

            "to_name": "book_sale",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {},
                "parameters": {},
                "body": null
            },

            "mappings": [

            {

                "source": "$",
                "target": "$['parameters']['DestinationKey']"

            }

            ]
        },

        {
            "from_name": "SeatCount",
            "from_type": "LOCAL_STORAGE",

            "to_name": "book_sale",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {},
                "parameters": {},
                "body": null
            },

            "mappings": [

            {

                "source": "$",
                "target": "$['parameters']['SeatCount']"

            }

            ]
        }

        ]
    };

    Apperyio.datasources = Apperyio.datasources || {};

    window.amount = Apperyio.datasources.amount = new Apperyio.DataSource(amount_service, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["welcome_amount_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {

        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["welcome_amount_onsuccess_mapping_0"]);
            toggle('welcome_mobilegrid_16', 'mob', 'true');
            toggle('welcome_btnBook', 'mob', 'true');
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });

    window.book_sale = Apperyio.datasources.book_sale = new Apperyio.DataSource(book_sale_service, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["welcome_book_sale_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {

        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["welcome_book_sale_onsuccess_mapping_0"]);
            var popupElement = Apperyio("welcomepopup");
            if (popupElement.popup("option", "positionTo") === "origin") {
                popupElement.popup("open", {
                    transition: "none",
                    positionTo: "#" + $(this).attr("id")
                });
            } else {
                popupElement.popup("open", {
                    transition: "none"
                });
            };
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });

    Apperyio.CurrentScreen = 'welcome';
    _.chain(Apperyio.mappings).filter(function(m) {
        return m.homeScreen === Apperyio.CurrentScreen;
    }).each(Apperyio.UIHandler.hideTemplateComponents);

    /*
     * Events and handlers
     */

    // On Load
    var welcome_onLoad = function() {
            welcome_elementsExtraJS();

            try {
                $a.c15r("mobilelabel_2", "set", "text", $a.storage["Name"].get("$"))
            } catch (e) {
                console.error(e)
            };

            welcome_deviceEvents();
            welcome_windowEvents();
            welcome_elementsEvents();
        };

    // screen window events


    function welcome_windowEvents() {

        $('#welcome').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });

    };

    // device events


    function welcome_deviceEvents() {
        document.addEventListener("deviceready", function() {

        });
    };

    // screen elements extra js


    function welcome_elementsExtraJS() {
        // screen (welcome) extra code

        /* mnuPlaces */

        $("#welcome_mnuPlaces").parent().find("a.ui-btn").attr("tabindex", "2");

        /* mnuNumseats */

        $("#welcome_mnuNumseats").parent().find("a.ui-btn").attr("tabindex", "3");

        /* welcomepopup */
        $("#welcome_welcomepopup").popup("option", "positionTo", "window");

    };

    // screen elements handler


    function welcome_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });

        $(document).off("click", '#welcome_mobileheader [name="btnAllSales"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('sales', {
                        reverse: false
                    });

                }
            },
        }, '#welcome_mobileheader [name="btnAllSales"]');

        $(document).off("click", '#welcome_mobilecontainer [name="btnQuote"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    try {
                        amount.execute({});
                    } catch (e) {
                        console.error(e);
                        hideSpinner();
                    };

                }
            },
        }, '#welcome_mobilecontainer [name="btnQuote"]');
        $(document).off("click", '#welcome_mobilecontainer [name="btnBook"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    try {
                        book_sale.execute({});
                    } catch (e) {
                        console.error(e);
                        hideSpinner();
                    };

                }
            },
        }, '#welcome_mobilecontainer [name="btnBook"]');

    };

    $(document).off("pagebeforeshow", "#welcome").on("pagebeforeshow", "#welcome", function(event, ui) {
        Apperyio.CurrentScreen = "welcome";
        _.chain(Apperyio.mappings).filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        }).each(Apperyio.UIHandler.hideTemplateComponents);
    });

    welcome_onLoad();
};

$(document).off("pagecreate", "#welcome").on("pagecreate", "#welcome", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    welcome_js();
});